import Image from 'next/image';
import './global.css';
import 'tailwindcss/tailwind.css';

export const metadata = {
  title: 'Welcome to instanvi-auth',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="mx-auto max-w-8xl px-6 pt-5 lg:px-8">
          <Image
            className="h-8 w-auto"
            src="/images/logo2.svg"
            alt=""
            width={100}
            height={35}
          />
          <div className="justify-center h-[90vh] w-full items-center flex  ">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
