export const contacts = [
  {
    id: 1,
    firstName: 'John',
    lastName: 'Doe',
    email: 'johndoe@gmail.com',
    phoneNumber: '688720586',
    whatsappNumber: '688720586',
    birthday: '17 Feb',
    address: 'Ndogbong 10eme',
    tags: ['adult ', 'male ', 'car ', 'food '],
    subscriptionStatus: 'Subscribed',
    isArchived: true,
    dateAdded: '14 July 2022',
    dateUpdated: '20 July 2022',
    source: 'USSD',
  },
  {
    id: 2,
    firstName: 'Michel',
    lastName: 'Mayers',
    email: 'mcmayers@gmail.com',
    phoneNumber: '693541586',
    whatsappNumber: '674541586',
    birthday: '03 May',
    address: 'Logpom Bassong',
    tags: ['adult ', 'female ', 'hair '],
    subscriptionStatus: 'Unsubscribed',
    isArchived: false,
    dateAdded: '11 April 2023',
    dateUpdated: '20 June 2023',
    source: 'Call',
  },
  {
    id: 3,
    firstName: 'Davis',
    lastName: 'Barns',
    email: 'db@gmail.com',
    phoneNumber: '688102586',
    whatsappNumber: '666720586',
    birthday: '11 Dec',
    address: 'Ndogbong 10eme',
    tags: ['adult ', 'male ', 'food ', 'car '],
    subscriptionStatus: 'Subscribed',
    isArchived: true,
    dateAdded: '14 July 2022',
    dateUpdated: '20 July 2022',
    source: 'USSD',
  },
  {
    id: 4,
    firstName: 'John',
    lastName: 'Doe',
    email: 'johndoe@gmail.com',
    phoneNumber: '688720586',
    whatsappNumber: '688720586',
    birthday: '17 Feb',
    address: 'Ndogbong 10eme',
    tags: ['adult ', 'male ', 'car '],
    subscriptionStatus: 'Subscribed',
    isArchived: true,
    dateAdded: '14 July 2022',
    dateUpdated: '20 July 2022',
    source: 'USSD',
  },
  {
    id: 5,
    firstName: 'Jefferson',
    lastName: 'Pierce',
    email: 'jp@gmail.com',
    phoneNumber: '688720586',
    whatsappNumber: '688720586',
    birthday: '12 Dec',
    address: 'Ndogbong 10eme',
    tags: ['animes ', 'movies ', 'fashion '],
    subscriptionStatus: 'Subscribed',
    isArchived: true,
    dateAdded: '14 July 2022',
    dateUpdated: '20 July 2022',
    source: 'USSD',
  },
  {
    id: 6,
    firstName: 'Remington',
    lastName: 'Smith',
    email: 'rsmith@gmail.com',
    phoneNumber: '688720586',
    whatsappNumber: '688720586',
    birthday: '17 Jan',
    address: 'London',
    tags: [],
    subscriptionStatus: 'Unsubscribed',
    isArchived: true,
    dateAdded: '14 July 2022',
    dateUpdated: '20 July 2022',
    source: 'USSD',
  },
];
