import React, { ReactNode } from 'react';
import { PeopleSidebar } from './components';
import './layout.scss';

export const metadata = {
  title: 'People | Instanvi Advertiser',
  description: 'Generated by create-nx-workspace',
};

interface RootLayoutProps {
  children: ReactNode;
  types: never;
}

const PeopleLayout = ({ children }: RootLayoutProps) => {
  return (
    <div className="people-layout">
      <div className="sidebar">
        <PeopleSidebar />
      </div>
      <div className="main">
        <div className="main-sub">{children}</div>
      </div>
    </div>
  );
};

export default PeopleLayout;
