import React, { ReactNode } from 'react';
import './layout.scss';

export const metadata = {
  title: 'People | Instanvi Advertiser',
  description: 'Generated by create-nx-workspace',
};

interface RootLayoutProps {
  children: ReactNode;
  types: never;
}

const PeopleLayout = ({ children }: RootLayoutProps) => {
  return <div>{children}</div>;
};

export default PeopleLayout;
