import './global.css';
import AuthGuard from './guards/authGuard';

export const metadata = {
  title: 'Welcome to advertiser-dsp',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthGuard>{children}</AuthGuard>
      </body>
    </html>
  );
}
