export type Persona = {
  age: string[];
  carrier_isp: string[];
  created_at: Date;
  device_type: string[];
  ethnicity: string[];
  gender: string[];
  image: string[];
  income_level: string[];
  interests: string[];
  language: string[];
  location: string[];
  name: string;
  occupation: string[];
  off_limit: string[];
  operating_system: string[];
  sensitive_exclusion: string[];
  sex: string[];
  social_status: string[];
  uuid: string;
  website: string[];
};
